[package]
name = "lpc8xx_bootapi"
description = "Invoke LPC8xx boot ROM APIs from Rust"
version = "0.1.0"
authors = ["ikubaku <hide4d51@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/ikubaku/lpc8xx_bootapi"

[dependencies]
